version: "3.7"
services:
  angular-cutter:
    # build: .
    image: 1dcutterangular
    ports:
      - "80:80"
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"
